Allow Alertmanager correlation and resolve, fix meta names with ':'
collectd/collectd pull request #4056
Opened 2022-10-17 08:19 UTC by carlospeon

ChangeLog: write_http plugin: Allow Alertmanager correlation and resolve.

In order to resolve alerts in Alertmanager:
- Move "severity" from labels to annotations, so "OKAY" notifications can match non okay notifications.
- Add "endsAt" date for "OKAY" notifications to clear the alert.
- Fix meta keys with invalid char ':', i.e. "network:received=true"

2022-11-08 12:26 UTC, mrunge approved these changes
Thank you!

2022-11-08 12:27 UTC, mrunge requested changes
could you please run  
```
contrib/format.sh src/utils/format_json/format_json.c 
```

2022-11-08 12:58 UTC, carlospeon commented
> could you please run
> 
> ```
> contrib/format.sh src/utils/format_json/format_json.c 
> ```

Sure, my bad.

2022-11-28 13:44 UTC, mrunge approved these changes

2022-11-28 13:45 UTC, merged