[collectd 6] processes plugin: Migrate to collectd 6 data structures.
collectd/collectd pull request #4273
Opened 2024-02-06 09:33 UTC by octo

ChangeLog: processes plugin: The metric schema has been aligned with OpenTelemetry semantic conventions.

2024-02-13 12:38 UTC, eero-t commented
Btw. do the open issues and PRs related to processes plugin have anything that should be taken into account here?
* Short-lived process handling:
  - https://github.com/collectd/collectd/issues/3026
  - https://github.com/collectd/collectd/pull/3027
* https://github.com/collectd/collectd/issues/2846
* https://github.com/collectd/collectd/pull/4122
* https://github.com/collectd/collectd/pull/1157

2024-02-13 15:27 UTC, eero-t requested changes
Hard to review as this is so huge, IMHO it would have been better as split into multiple PRs. I think I noticed couple of bugs though.

PS. following PRs could do further cleanups:
*  split FreeBSD/NetBSD/OpenBSD and AIX cmdline parsing into a separate functions, similarly to how it's done for Linux & Solaris
* Order `process_count[<state>] = 0` statements and switch cases alphabetically so that it's easier to check them against each other

(Not doing them in this PR, or rebasing things until merging, helps the review.)

2024-02-13 15:27 UTC, eero-t commented on src/processes.c
> +  long long cpu_system_counter = atoll(fields[12]);
line 1576 could have comment like:
`// field numbers are ones listed for 'stat' file in 'man proc' - 3`

2024-02-24 22:17 UTC, octo reviewed
Thanks for your review @eero-t! I realize this PR is way too large. I should have started refactoring the code as it was very convoluted and it's still more complicated than I'd like. Alas, by the time I realized the extend I was into too deep 🫤

2024-02-24 22:17 UTC, octo commented on src/processes.c
> +            ((fpcounter_t)task_absolutetime_info.total_system) / 1e9;
I think the original code was incorrect: according to https://codereview.chromium.org/16818003 the uint64_t contain nanoseconds. Unfortunately Apple's documentation doesn't say anything about the unit of these counter :(

2024-02-24 22:17 UTC, octo commented on src/processes.c
> +  ssize_t n = read_text_file_contents("/proc/stat", buffer, sizeof(buffer) - 1);
✅ done

2024-02-24 22:17 UTC, octo commented on src/processes.c
> +    ps_submit_proc_list(ps);
✅ done

2024-02-24 22:17 UTC, octo commented on src/processes.c
> +          .command_line = cargs,
Wow, good catch!

✅ done

2024-02-26 14:26 UTC, eero-t commented on src/processes.c
> +      return EINVAL;
Ok, let's leave this as reminder for that potential future PR.

2024-02-26 14:44 UTC, eero-t approved these changes
Checked the earlier commented items and new commits (I assume rebase did not change earlier ones).   Review is somewhat superficial due to the huge amount of changes, but that's best I could do => approved.

2024-02-26 16:00 UTC, octo commented
Thanks @eero-t!

2024-02-26 16:00 UTC, merged