clang: fix compilation by ignoring a warning
collectd/collectd pull request #4309
Opened 2024-05-08 01:16 UTC by jvsg

Fixes: #4308

2024-05-08 08:41 UTC, eero-t commented
Changed title to better describe what is being fixed, and added the required (Fix) label & "ChangeLog" entry.

2024-05-08 08:55 UTC, eero-t requested changes
If the warned macro issue cannot be fixed (I know very little of Perl, so I have no idea how hard that would be), at least the `#if` guard should be fixed to check for correct compiler version.

2024-05-08 08:55 UTC, eero-t commented on src/perl.c
> +#endif
According to:
* https://reviews.llvm.org/D86751
* https://github.com/Perl/perl5/issues/18780

It's a **new** option that came with Clang-12 around 2021.

Also, Clang is not Apple specific, and one could be using GCC on Apple.

=> I think this should be changed to ignore the diagnostic for Clang >= 12, not for Apple.

2024-05-08 09:00 UTC, eero-t commented
@mrunge, do you have Linux setup for checking whether Perl plugin has same issue with current Linux Clang / or any other comments on this?

(I don't have any Perl dev stuff on my setup, and I'd rather keep it out of it, as I'm rather a Python user. :-))

2024-05-08 09:02 UTC, eero-t commented
Commit title should be also be fixed, to indicate that it's the perl plugin that is being fixed (not clang one).

2024-05-20 14:02 UTC, jvsg commented
@eero-t please re-review

2024-05-20 14:31 UTC, eero-t approved these changes
Thanks, this looks fine now!  => Triggered checks & approved.

2024-05-20 15:08 UTC, eero-t commented
The only failure is unrelated (https://github.com/collectd/collectd/pull/4298).

Before merging, I would a comment from somebody who uses (or at least builds) Perl plugin.  @mrunge?

2024-05-21 16:09 UTC, mrunge commented
I am not using the perl plugin, and I'm also not building collectd on a regular basis anymore, so can't add test cases or feedback to this.

2024-05-21 16:10 UTC, mrunge commented
@jvsg thank you for your PR, it looks good to me.

2024-05-21 16:10 UTC, merged