Update README.md
collectd/collectd pull request #4318
Opened 2024-07-12 06:53 UTC by LeavesMountains

Changelog: Fix MarkDown syntax errors in README.md

# Fixed syntax errors in the file and optimized the format of the document

## examples

- before:
<img width="883" alt="image" src="https://github.com/user-attachments/assets/f2496969-22d1-4f82-9a55-809a55c1c37e">

- now:
<img width="671" alt="image" src="https://github.com/user-attachments/assets/d3e073f1-0a77-49a1-bf4a-c8a69f41f840">

- before:
<img width="877" alt="image" src="https://github.com/user-attachments/assets/c1657cc0-a8bc-4b89-9b8b-6743a772e997">

- now:
<img width="650" alt="image" src="https://github.com/user-attachments/assets/274ef3df-a384-4030-a96c-d72fc1078275">

2024-07-12 09:04 UTC, eero-t requested changes
MarkDown format seems indeed been intended for README, typographical conventions for English text just hadn't been updated yet: https://github.com/collectd/collectd/issues/3052

However, besides fixing MarkDown syntax, your changes also break the document fitting into 80 columns (while legacy, docs are still read also directly, not just thorough MarkDown parsers).  Please remove such redundant reformatting of the text, and have just the MarkDown syntax fixes. It will then be also easier review.

After that, you need to add `ChangeLog:` entry to the PR description for it to pass CI.

PS. You could tell in your commit message which earlier change it fixes (https://github.com/collectd/collectd/pull/4115):
`Fixes: 8286d53f7c`

2024-07-12 10:16 UTC, eero-t reviewed
Thanks for the quick update, this is much easier to review!

Not all of the quotes should be converted to monotype, some are just names that should be quoted, and others are links.    And you might as well also monotype all file names in the README for consistency.

2024-07-12 10:16 UTC, eero-t commented on README.md
> +    Used for the plugin `barometer`, provides just the i2c-dev.h header file
```suggestion
    Used for the plugin `barometer`, provides just the `i2c-dev.h` header file
```

2024-07-12 10:16 UTC, eero-t commented on README.md
>      Note: the library should be build with -fPIC flag to be linked with
```suggestion
    Note: the library should be build with `-fPIC` flag to be linked with
```

2024-07-12 10:16 UTC, eero-t commented on README.md
> +    Library that encapsulates the `Java Virtual Machine` (JVM). This library is
Whyt this would be shown as monospace?
```suggestion
    Library that encapsulates the Java Virtual Machine (JVM). This library is
```

2024-07-12 10:16 UTC, eero-t commented on README.md
> +    Used by the `routeros` plugin to connect to a device running `RouterOS`.
```suggestion
    Used by the `routeros` plugin to connect to a device running _RouterOS_.
```

2024-07-12 10:16 UTC, eero-t commented on README.md
>      libusb, libftdi and libudev.
```suggestion
    Used by the `sigrok` plugin. In addition, `libsigrok` depends on `glib`,
    `libzip`, and optionally (depending on which drivers are enabled) on
    `libusb`, `libftdi` and `libudev`.
```

2024-07-12 10:16 UTC, eero-t commented on README.md
> +  section `Prerequisites` above) and rerun `configure`. If you specify the
Document links should be links, not in monotype.

2024-07-12 10:16 UTC, eero-t commented on README.md
> +  details. If you pass DESTDIR=<path> to `make install`, <path> will be
```suggestion
  details. If you pass `DESTDIR=<path>` to `make install`, `<path>` will be
```

2024-07-12 10:16 UTC, eero-t commented on README.md
> +  and many contributors (see `AUTHORS`).
Links should be specified as links.

2024-07-12 10:16 UTC, eero-t commented on README.md
>      Used by the redis plugin. Please note that you require a 0.10.0 version
```suggestion
    Used by the `redis` plugin. Please note that you require a 0.10.0 version
```

2024-07-12 10:16 UTC, eero-t commented on README.md
>    packet sniffer ("<iface>: PACKET SNIFFER(/usr/sbin/collectd[<pid>])"). The
```suggestion
  If you are using the `dns` plugin,  `chkrootkit(1)` will report `collectd` as a
  packet sniffer (`<iface>: PACKET SNIFFER(/usr/sbin/collectd[<pid>])`). The
```

2024-07-12 10:16 UTC, eero-t commented on README.md
>        daemon (RRDcacheD) - see rrdcached(1). That daemon provides a general
```suggestion
      daemon (RRDcacheD) - see `rrdcached(1)`. That daemon provides a general
```

2024-07-12 10:16 UTC, eero-t commented on README.md
> +      Plugin to read values from `The Energy Detective` (TED).
```suggestion
      Plugin to read values from "The Energy Detective" (TED).
```

2024-07-12 10:16 UTC, eero-t commented on README.md
> +      Pages swapped out onto hard disk or whatever is called `swap` by the OS..
```suggestion
      Pages swapped out onto hard disk or whatever is called `swap` by the OS.
```

2024-07-12 10:16 UTC, eero-t commented on README.md
> +      Integrates a `Java Virtual Machine` (JVM) to execute plugins in Java
```suggestion
      Integrates a Java Virtual Machine (JVM) to execute plugins in Java
```

2024-07-12 10:16 UTC, eero-t commented on README.md
> +      Statistics about Ascent, a free server for the game `World of Warcraft`.
```suggestion
      Statistics about Ascent, a free server for the game "World of Warcraft".
```

2024-07-12 11:49 UTC, eero-t commented on README.md
> +      Plugin to read values from `The Energy Detective` (TED).
Everything else looks now fine (thanks for the extra items I had missed), but according to quick Googling, this **is** capitalized, not written as `"the energy detective" (ted)`?

2024-07-12 11:52 UTC, eero-t commented
> Changelog: entry to the PR description for it to pass CI.

This should be one-liner description of the changes done in the PR (see other PRs for examples).
 
> Fixes: [8286d53](https://github.com/collectd/collectd/commit/8286d53f7cab2457ddb491153345700451603ae3)

This should be in the _commit_ description, not in the PR description (it's fine if you squash changes to a single commit).

2024-07-17 11:45 UTC, eero-t commented on README.md
> +      Plugin to read values from `The Energy Detective` (TED).
Will replace this with up to date comment.

2024-07-17 11:51 UTC, eero-t requested changes
Changed in description:
> Changelog: Fix syntax errors in README.md, and undo formatting changes

To:
> Changelog: Fix MarkDown syntax errors in README.md

As undos were for changes done within this PR, instead of changes for the  _original_ README.

2024-07-17 11:51 UTC, eero-t commented on README.md
> +      plugin to read values from "the energy detective" (ted).
Other plugin entries are capitalized, and according to quick Googling, TED **is** also capitalized:
```suggestion
      Plugin to read values from "The Energy Detective" (TED).
```

2024-07-18 02:26 UTC, LeavesMountains commented
@eero-t Hello, If it is convenient, please check the PR:)

2024-07-18 16:57 UTC, eero-t reviewed
Sorry, I noticed couple of additional issues in the changes.

After you fix these, you could squash the changes into a single commit before I merge it.

2024-07-18 16:57 UTC, eero-t commented on README.md
> +  and many contributors (see [AUTHORS](https://github.com/collectd/collectd/graphs/contributors)).
"AUTHORS" should link authors, not contributors:
```suggestion
  and many other [authors](AUTHORS) and [contributors](https://github.com/collectd/collectd/graphs/contributors).
```

2024-07-18 16:57 UTC, eero-t commented on README.md
> +  ``implementation`` the configure script needs to compile and run a short
Quotation is more appropriate here than monospace font:
```suggestion
  "implementation" the configure script needs to compile and run a short
```

2024-07-19 04:53 UTC, LeavesMountains commented
Thank you for your suggestion. @eero-t 

I noticed that this syntax does not seem to be correctly recognized by markdown:

`Florian octo Forster <octo at collectd.org>` at line 1216
`Sebastian tokkee Harl <sh at tokkee.org>` at line 1217
...

"<example.com>" does not seems to be correct link syntax.

![image](https://github.com/user-attachments/assets/bc5c65e2-652f-42eb-8e7a-e9881eaeee02)


I am not sure whether this needs to be modified.

2024-07-19 07:57 UTC, eero-t commented
> I noticed that this syntax does not seem to be correctly recognized by markdown:
> 
> `Florian octo Forster <octo at collectd.org>` at line 1216 `Sebastian tokkee Harl <sh at tokkee.org>` at line 1217 ...
> 
> "<example.com>" does not seems to be correct link syntax.

Mail addresses are written with spaces to avoid their automatic collection by spambots, so I don't think turning them into MarkDown compatible email links would be correct.

They could be quoted like terminal commands `<foobar at example.com>`,   but I think writing them with `()` instead of `<>` would be fine too.

2024-07-19 08:58 UTC, matwey commented
> > I noticed that this syntax does not seem to be correctly recognized by markdown:
> > 
> > `Florian octo Forster <octo at collectd.org>` at line 1216 `Sebastian tokkee Harl <sh at tokkee.org>` at line 1217 ...
> > 
> > "<example.com>" does not seems to be correct link syntax.
> 
> Mail addresses are written with spaces to avoid their automatic collection by spambots, so I don't think turning them into MarkDown compatible email links would be correct.

I am not sure that modern spam bots are so stupid.

Also, nobody prevents them to git-clone each and every public repo on GitHub to collect mail addresses.

> 
> They could be quoted like terminal commands `<foobar at example.com>`,   but I think writing them with `()` instead of `<>` would be fine too.

2024-07-19 09:25 UTC, eero-t approved these changes

2024-07-19 11:06 UTC, eero-t commented
> I am not sure that modern spam bots are so stupid.

I know, but I'm neither of those authors, so it's better to leave addresses as-is, until they get involved.

I'll squash your commits on merge, so the changes are easier to read (= no reverts).

Thanks for fixing the README!

2024-07-19 11:09 UTC, merged